steps:
  - label: Build and test with GHC 9.0.2
    command: |
      nix build -L --keep-going --no-link .#ghc902/ci
    timeout: 100
  - label: Build and test with GHC 9.2.5
    command: |
      nix build -L --keep-going --no-link .#ghc925/ci
    timeout: 100
  - wait
  - label: Check formatting
    command: |
      nix develop .#cabalAndOrmolu -c ./format.sh
      git diff --exit-code --color=always
  - wait
  - label: Build and deploy Ormolu Live
    command: |
      if [[ $BUILDKITE_BRANCH == "master" ]]; then
        ormolu-live/deploy.sh
      else
        nix build -L -j 1 .#ormoluLive/no-code
      fi
    timeout: 100
