name: CI
on:
  pull_request:
  push:
    branches:
      - 'amesgen/flakeify-ci-test'
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ghc: [ghc902, ghc925]
    name: Build and test on ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            accept-flake-config = true
      - name: Build and run tests
        run: |
          nix build -L --keep-going --no-link .#${{ matrix.ghc }}/ci
  lint:
    needs: ci
    name: Formatting and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            accept-flake-config = true
      - name: Format via Cabal and Ormolu
        run: nix run .#format
      - name: pre-commit-check
        run: nix build -L --no-link .#pre-commit-check
