name: Build static binary
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build static binary
        run: |
          docker run \
            -v $(pwd):/mnt -w /mnt \
            utdemir/ghc-musl:v14-ghc8101 \
            bash .github/workflows/build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ormolu
          path: ormolu
